### ISSUE TITLE
Could you share the gulp file, tools to build SCSS, JS and tools when we start build a theme?

### ISSUE THREAD

**Issue by NautHnim** [webmandesign/webman-theme-framework#1]

**Comment by webmandesign** [comment]
Hi,

I'm sorry, but I don't use Gulp or any other similar tool.
For SASS compiling I use https://prepros.io on Windows.
I code JS and other files directly in https://www.sublimetext.com with no additional tool.

Regards,

Oliver

**Comment by webmandesign** [comment]
BTW, all my themes are based on https://underscores.me starter theme, so you can definitely start there.
